spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres_db}
    username: ${DB_USER:postgres_user}
    password: ${DB_PASS:postgres_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /api-docs
    enabled: true

open:
  api:
    title: API Service Document
    version: v1.0.0
    description: This is a backend service
    server: http://localhost:8080/api/backend-service
    serverDes: Local backend service

jwt:
  secret: ${JWT_SECRET:my-super-secret-key-my-super-secret-key-my-super-secret-key}
  expiration: ${JWT_ACCESS_EXPIRY:900}
  refresh-duration: ${JWT_REFRESH_EXPIRY:604800}

server:
  port: 8080
  servlet:
    context-path: /api/backend-service
